AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM app that uses Rekognition APIs to detect text in S3 Objects and stores
  labels in DynamoDB
Resources:
  DetectTextInImage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.lambda_handler
      Runtime: ruby2.5
      Environment:
        Variables:
          TABLE_NAME:
            Ref: ResultsTable
      Policies:
      - S3ReadPolicy:
          BucketName: rays-image-text-bucket
      - RekognitionDetectOnlyPolicy: {}
      - DynamoDBCrudPolicy:
          TableName:
            Ref: ResultsTable
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceImageBucket
            Events:
            - s3:ObjectCreated:*
      CodeUri: s3://test-sam-image-rekognition/751b3a591e74a08af499658c9dc77dd3
  SourceImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: rays-image-text-bucket
  ResultsTable:
    Type: AWS::Serverless::SimpleTable
